# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src', 'src'),
        ('resources', 'resources'),
    ],
    hiddenimports=[
        # Python标准库
        'platform',
        'winreg',
        'pathlib',
        'json',
        'sqlite3',
        'gzip',
        'hashlib',
        'datetime',
        'threading',
        'logging',
        'dataclasses',
        'enum',
        'typing',
        'copy',
        'base64',
        'io',
        # 项目模块
        'views',
        'views.main_window',
        'views.components',
        'views.components.history_list',
        'views.components.search_bar',
        'views.components.tray_icon',
        'views.components.settings_dialog',
        'views.components.data_dialog',
        'views.styles',
        'views.styles.main_style',
        'controllers',
        'controllers.clipboard_controller',
        'controllers.hotkey_controller',
        'models',
        'models.clipboard_item',
        'services',
        'services.clipboard_service',
        'config',
        'config.settings',
        'utils',
        'utils.logger',
        'utils.startup',
        # PyQt6
        'PyQt6.sip',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'tkinter',
        'unittest',
        'pytest',
        'email',
        'http',
        'xml',
        'distutils',
        'setuptools',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ClipMasterPro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)